# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [2]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [144]:
import numpy as np
import timeit

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
print(np.__version__)

1.26.4


#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
vec = np.zeros(10)
print(vec)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [25]:
vec.itemsize


8

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [13]:
np.add?

Signature:       np.add(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'add'>
File:            /opt/anaconda3/lib/python3.12/site-packages/numpy/__init__.py
Docstring:      
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [15]:
vec = np.zeros(10)
vec[4] = 1
print(vec)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [17]:
vec = np.arange(10, 50)
print(vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [18]:
print(vec[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [20]:
mat = np.arange(9).reshape(3, 3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [21]:
vec = np.array([1, 2, 0, 0, 4, 0])
np.where(vec != 0)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [22]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [33]:
array3d = np.random.rand(3,3,3)
print(array3d)

[[[0.02925449 0.76282698 0.19055631]
  [0.37449064 0.59023957 0.92631955]
  [0.73641952 0.95086994 0.77642416]]

 [[0.36051465 0.78502893 0.59787873]
  [0.24524886 0.6734021  0.27627809]
  [0.0888909  0.20490375 0.14834448]]

 [[0.14681476 0.44372125 0.27524803]
  [0.26140062 0.06583712 0.56930858]
  [0.26004656 0.55418858 0.24776516]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [32]:
bigarray = np.random.rand(10,10)
max = np.max(bigarray)
min = np.min(bigarray)
print(max, min)

0.9971805520161668 0.007793047567367428


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [34]:
vec = np.random.rand(30)
print(np.mean(vec))

0.5202875281748748


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [40]:
arr = np.zeros(100).reshape(10,10)

arr[0,:] = 1
arr[:,0] = 1
arr[:,-1] = 1
arr[-1,:] = 1
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [41]:
rand_arr = np.random.rand(4,5)
def border_fill(array, fill):
    array[0,:] = fill
    array[:,0] = fill
    array[:,-1] = fill
    array[-1,:] = fill
    return array

print(border_fill(rand_arr, 0))

[[0.         0.         0.         0.         0.        ]
 [0.         0.79472473 0.16904594 0.53755511 0.        ]
 [0.         0.53846513 0.52384006 0.92058446 0.        ]
 [0.         0.         0.         0.         0.        ]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [44]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [51]:
mat = np.eye(5)
for i in range(1, mat.shape[0]):
    mat[i, i-1] = i
print(mat)

[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [0. 2. 1. 0. 0.]
 [0. 0. 3. 1. 0.]
 [0. 0. 0. 4. 1.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [54]:
board = np.zeros(64).reshape(8,8)
for i in range(board.shape[0]):
    for j in range(board.shape[1]):
        if i%2 == 0 and j%2 == 0:
            board[i,j] = 1
        elif i%2 == 1 and j%2 == 1:
            board[i,j] = 1
        else:
            continue

print(board)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [55]:
answer(19)

Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [59]:
arr = np.random.rand(6,7,8)
flat_arr = arr.flatten()
val_100 = flat_arr[99]
print(np.where(arr == val_100))

print(np.unravel_index(99,(6,7,8)))

(array([1]), array([5]), array([3]))
(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [64]:
base1 = np.array([[1,0],[0,1]])
print(base1)
print(np.tile(base1, (4,4)))

[[1 0]
 [0 1]]
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [70]:
mat = np.random.rand(5,5)
mat_norm = mat / np.sum(mat)
print(mat_norm)

mat_norm2 = (mat - np.mean(mat)) / np.std(mat)
print(mat_norm2)

[[0.06831046 0.00265723 0.03431824 0.02974503 0.03382009]
 [0.06341868 0.03518083 0.06236577 0.07107528 0.03115663]
 [0.00277837 0.03833001 0.06442351 0.04386962 0.00730339]
 [0.02918965 0.05100412 0.06005627 0.05602904 0.06476052]
 [0.00172912 0.0165268  0.03728681 0.0357041  0.05896041]]
[[ 1.32186037 -1.74359291 -0.26529015 -0.47882083 -0.28854983]
 [ 1.09345508 -0.22501456  1.04429338  1.45095414 -0.41291114]
 [-1.73793688 -0.0779744   1.14037227  0.18067883 -1.52665662]
 [-0.50475228  0.51379968  0.93645921  0.74842144  1.1561078 ]
 [-1.78692781 -1.09600092 -0.12668313 -0.20058245  0.88529171]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [72]:
color = np.dtype([('r', np.ubyte),
                  ('g', np.ubyte),
                  ('b', np.ubyte),
                  ('a', np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [75]:
mat1 = np.random.rand(5,3)
mat2 = np.random.rand(3,2)
print(np.matmul(mat1, mat2))


[[1.23030613 0.96646667]
 [0.99384968 1.0515717 ]
 [0.7205739  0.65857414]
 [1.10467165 0.99670504]
 [0.85003605 1.05272856]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [79]:
arr = np.arange(10)
arr[4:8] = -arr[4:8]
print(arr)


[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [80]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [87]:
Z = np.arange(10)
print(Z)
print(Z**Z)
#2 << Z >> 2
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
#Z<Z>Z

[0 1 2 3 4 5 6 7 8 9]
[        1         1         4        27       256      3125     46656
    823543  16777216 387420489]
[False False False False False False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [88]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/var/folders/dm/kv9hbd5149s6d437c3799lbr0000gn/T/ipykernel_74195/548293649.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
/var/folders/dm/kv9hbd5149s6d437c3799lbr0000gn/T/ipykernel_74195/548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
/var/folders/dm/kv9hbd5149s6d437c3799lbr0000gn/T/ipykernel_74195/548293649.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([0.])

#### 29. How to round away from zero a float array ? (★☆☆)

In [92]:
Z = np.random.uniform(-10,+10,10)
print(np.ceil(np.abs(Z)))
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[ 7.  1.  2.  5. 10.  7.  4.  6.  8.  6.]
[  7.   1.  -2.  -5. -10.   7.   4.   6.  -8.  -6.]
[  7.   1.  -2.  -5. -10.   7.   4.   6.  -8.  -6.]


#### 30. How to find common values between two arrays? (★☆☆)

In [95]:
arr1 = np.arange(0,10)
arr2 = np.arange(5,15)
np.intersect1d(arr1, arr2)

array([5, 6, 7, 8, 9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [96]:
answer(31)

# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [101]:
#no 

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [103]:
today = np.datetime64('today')
tomorrow = today + np.timedelta64(1)
yesterday = today - np.timedelta64(1)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [108]:
output = [np.datetime64('2016-07', 'D') + np.timedelta64(i) for i in range(31)]
print(output)

print(answer(34))

[numpy.datetime64('2016-07-01'), numpy.datetime64('2016-07-02'), numpy.datetime64('2016-07-03'), numpy.datetime64('2016-07-04'), numpy.datetime64('2016-07-05'), numpy.datetime64('2016-07-06'), numpy.datetime64('2016-07-07'), numpy.datetime64('2016-07-08'), numpy.datetime64('2016-07-09'), numpy.datetime64('2016-07-10'), numpy.datetime64('2016-07-11'), numpy.datetime64('2016-07-12'), numpy.datetime64('2016-07-13'), numpy.datetime64('2016-07-14'), numpy.datetime64('2016-07-15'), numpy.datetime64('2016-07-16'), numpy.datetime64('2016-07-17'), numpy.datetime64('2016-07-18'), numpy.datetime64('2016-07-19'), numpy.datetime64('2016-07-20'), numpy.datetime64('2016-07-21'), numpy.datetime64('2016-07-22'), numpy.datetime64('2016-07-23'), numpy.datetime64('2016-07-24'), numpy.datetime64('2016-07-25'), numpy.datetime64('2016-07-26'), numpy.datetime64('2016-07-27'), numpy.datetime64('2016-07-28'), numpy.datetime64('2016-07-29'), numpy.datetime64('2016-07-30'), numpy.datetime64('2016-07-31')]
Z = np.

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [111]:
A = np.ones(3)
B = np.ones(3) * 2
np.add(A,B,out=B)
np.divide(A,2)
np.negative(A)
np.multiply(A,B, out=A)
print(A)

[3. 3. 3.]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [130]:
arr = np.random.uniform(0,10,25)
print(arr)

method1 = arr//1
print(method1)
method2 = arr - arr%1
print(method2)
method3 = arr.astype(int)
print(method3)


print(answer(36))

[3.96020937 5.35956088 4.61460975 7.01557847 5.99768341 9.60638041
 9.01781252 3.82558046 1.23714194 4.5457099  6.01888046 2.58147137
 9.8612923  2.19031967 2.1054265  7.15485429 6.90148712 3.97694797
 6.86003909 3.56821023 7.44725964 3.81519968 5.69491569 8.92011227
 9.51475465]
[3. 5. 4. 7. 5. 9. 9. 3. 1. 4. 6. 2. 9. 2. 2. 7. 6. 3. 6. 3. 7. 3. 5. 8.
 9.]
[3. 5. 4. 7. 5. 9. 9. 3. 1. 4. 6. 2. 9. 2. 2. 7. 6. 3. 6. 3. 7. 3. 5. 8.
 9.]
[3 5 4 7 5 9 9 3 1 4 6 2 9 2 2 7 6 3 6 3 7 3 5 8 9]
Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))
None


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [115]:
row = np.arange(5)
mat = np.tile(row, 5).reshape(5,5)
print(mat)

print(answer(37))

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

# without broadcasting
Z = np.tile(np.arange(0, 5), (5,1))
print(Z)
None


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [132]:
print(np.array(range(10)))

print(answer(38))

[0 1 2 3 4 5 6 7 8 9]
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)
None


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [134]:
print(np.linspace(0.1, 1, num=10, endpoint=False))

print(answer(39))

[0.1  0.19 0.28 0.37 0.46 0.55 0.64 0.73 0.82 0.91]
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)
None


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [138]:
print(np.sort(np.random.rand(10)))

print(answer(40))

[0.17661279 0.37424822 0.41953116 0.53526477 0.59291552 0.6878167
 0.69712587 0.69977388 0.71721541 0.96251161]
Z = np.random.random(10)
Z.sort()
print(Z)
None


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [153]:
#arr = np.arange(10)

timeit.timeit(stmt='import numpy as np;arr = np.arange(10);np.sum(arr)')
#timeit.timeit(stmt='import numpy as np;arr = np.arange(10);np.add.reduce(arr)')

#print(answer(41))

1.13127729203552

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [155]:
A = np.random.rand(10)
B = np.random.rand(10)
print(A == B)


print(answer(42))

[False False False False False False False False False False]
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)
None


#### 43. Make an array immutable (read-only) (★★☆)

In [160]:
answer(43)

Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [179]:
cart = np.random.rand(10,2)
rad = np.sqrt(cart[:, 0]**2 + cart[:, 1]**2)
theta = np.arctan2(cart[:, 1], cart[:, 0])
polar = np.array(list(zip(rad, theta)))


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [183]:
vec = np.random.rand(10)
vec[np.where(vec == np.max(vec))] = 0



#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)